### ISSUE TITLE
Candlegenie Bot

### ISSUE THREAD

**Issue by uu3331448** [AssaEmpireToken/Pancakeswap-Prediction-Bot-2022-Updated#32]
Hi,

Any idea why when I run the command "npm run cg" the terminal displays this (see attached pic), but nothing initializes? I have left it running for hours and nothing. It has yet to start a round.
![CandleGenie](https://user-images.githubusercontent.com/107694952/174307828-c74d8b90-e850-4314-ba27-b645d52aecfc.JPG)

**Comment by AssaEmpireToken** [comment]
Candlegenie dont work i think. Try on PancakeSwap and use npm run start
